sudo: required
dist: trusty

language: cpp

services:
    - docker

before_install:
    - docker pull htfy96/build-image
    - docker run -ti -v $(pwd):/data htfy96/build-image bash -c "cd /data; mkdir -p build && cd build; cmake -Dgo-ai_build_tests=ON -DCMAKE_C_COMPILER=${X_CC} -DCMAKE_CXX_COMPILER=${X_CXX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .." 

script:
    - docker run -ti -v $(pwd):/data htfy96/build-image bash -c 'cd /data/build; make -j4'
    - docker run -ti -v $(pwd):/data htfy96/build-image bash -c 'cd /data/build; ctest --output-on-failure'

matrix:
  include:
    - env: 
          - X_CC=gcc-5
          - X_CXX=g++-5
          - BUILD_TYPE=Debug
    - env: 
          - X_CC=gcc-5
          - X_CXX=g++-5
          - BUILD_TYPE=Release
    - env: 
          - X_CC=clang-3.8
          - X_CXX=clang++-3.8
          - BUILD_TYPE=Debug
    - env:
          - X_CC=clang-3.8
          - X_CXX=clang++-3.8
          - BUILD_TYPE=Release
